server {
    server_name everythingsoil.com www.everythingsoil.com;

    client_max_body_size 50M;

    location /static/ {
        alias /data/everythingsoil/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /data/everythingsoil/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        include uwsgi_params;
        uwsgi_pass unix:///data/everythingsoil/uwsgi.sock;
        uwsgi_read_timeout 300;
        uwsgi_connect_timeout 300;
        uwsgi_send_timeout 300;
    }

    listen 80;
    listen [::]:80;
}
