[uwsgi]
# Directory and application configuration
chdir           = /data/everythingsoil
module          = ets.wsgi:application
home            = /data/everythingsoil/venv

# Process management
master          = true
processes       = 4
threads         = 2

# Socket configuration for Nginx communication
socket          = /data/everythingsoil/uwsgi.sock
chmod-socket    = 666
vacuum          = true

# Logging & Environment
env             = DJANGO_SETTINGS_MODULE=ets.settings.prod
max-requests    = 5000
buffer-size     = 32768
